Artemiev tasks
IlyaOrlov/PythonCourseSTM pull request #11
Opened 2021-06-26 15:31 UTC by ArtemijArtemev

lecture two's home work

2021-06-26 19:51 UTC, IlyaOrlov requested changes

2021-06-26 19:51 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +# -*- coding: utf-8 -*-
Этот коммент нужен только в Python2.

2021-06-26 19:51 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +    if len(nums) < 2: return nums[0]
А если nums пустой? И лучше return на следующую строку вынести, исходя из кодинг стайла (не писать больше одно выражения в одной строке).

2021-06-26 19:51 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +def max_num(*args):
Данная функция возвращает большее из значений args. Еще хотелось бы увидеть функцию, которая выводит большее значение на экран (согласно заданию).

2021-06-26 19:51 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/game.py
> +    def handle_item(self, item):
Отлично! Таким образом подобранный предмет может количественно менять тот или иной параметр персонажа. Вопрос для размышления: как можно реализовать возможность качественной замены тех или иных методов персонажа в случае подбора предмета? Например, при подборе каких-то крутых снарядов анимация стрельбы (реализация метода shoot) полностью бы менялась. Намек: shoot - это фактически просто имя переменной, указывающей на соответствующую функцию, и можно сделать так, чтоб она указывала, на другую функцию.

2021-06-28 17:34 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/min_max.py
> +# -*- coding: utf-8 -*-
убран

2021-06-28 17:35 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/min_max.py
> +    if len(nums) < 2: return nums[0]
выбрасываем исключение при отсуствии аргументов

2021-06-28 17:35 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/min_max.py
> +def max_num(*args):
добавлено

2021-06-28 17:36 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/game.py
> +    def handle_item(self, item):
делаем ссылку на другой метод

2021-06-28 18:05 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +    n_count = len(nums)
Необязательно сохранять длину в отдельную переменную. len не пересчитывает элементы в стандартном контейнере, а обращается к встроенному в контейнер счетчику.

2021-06-28 18:07 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/game.py
> +    def handle_item(self, item):
Да. А если реализовать для таких методов отдельную иерархию, мы получим реализацию паттерна стратегия https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2021-06-28 18:12 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +    actual = nums.pop()
pop не просто возвращает элемент из списка, но извлекает его. Довольно неожиданно будет при передаче списка в функцию, которая просто ищем минимум или максимум, обнаружить, что этот список вдруг поменялся. Поэтому лучше просто обратиться по индексу.

2021-06-28 18:37 UTC, IlyaOrlov requested changes

2021-06-28 18:37 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +    for number in nums:
Чтоб не делать лишних проверок (т.к. operator по ходу цикла меняться не будет), можно заранее определить операцию сравнения:
```python
if operator == 'min':
    cmp = lambda x, y: x < y
else:
    cmp = lambda x, y: x > y
```
или то же самое в одну строку:
```python
cmp = (lambda x, y: x < y) if operator == 'min' else (lambda x, y: x > y)
```
Тогда цикл получится следующим:
```python
for number in nums:
    if cmp(number, actual):
        actual = number
```

2021-06-28 18:37 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +print_max_num(1, -1, 100000)
Рекомендуется в конце файла оставлять ровно одну пустую строку. Чтоб иметь меньше проблем с текстовыми редакторами в различных ОС.

2021-06-29 19:11 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/min_max.py
> +    n_count = len(nums)
можно сэкономить на памяти либо на вычислениях(обращениях к свойствам контейнеров). в зависимости от ситуации.

2021-06-29 19:12 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/min_max.py
> +    actual = nums.pop()
тут согласен

2021-06-29 19:28 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/min_max.py
> +    for number in nums:
да, красивее выглядит)

2021-06-29 20:13 UTC, IlyaOrlov commented on Practice/Artemiev/lecture2/min_max.py
> +    n_count = len(nums)
А на памяти как? n_count тут просто указывает на то же значение, что и соответствующий атрибут контейнера. При этом сама переменная n_count как раз память и занимает. По времени выигрыша также практически нет.

2021-06-29 20:46 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/game.py
> +    def handle_item(self, item):
да, так, лучше.

2021-06-29 20:48 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture2/min_max.py
> +    n_count = len(nums)
снова подзабыл что в питоне почти все объект.

2021-06-29 21:46 UTC, IlyaOrlov approved these changes

2021-06-29 21:47 UTC, merged