Lapshina
IlyaOrlov/PythonCourseSTM pull request #14
Opened 2021-06-27 21:36 UTC by LapshinaAnnna

2021-06-28 07:52 UTC, IlyaOrlov requested changes
Все ОК. Только все файлы с решениями надо перенести в папку Practice/ваша_папка

2021-06-28 07:52 UTC, IlyaOrlov commented on Tasks/pep8task.py
> +            f = open(output, 'r')
А вот стоит ли строки 34-35 сдвигать внутрь цикла? Получается, в цикле мы заполняем контейнер self.map и каждый раз перезаписываем его в файл. Если вынести из цикла, то контейнер запишется в файл только один раз, когда заполнится.

2021-06-28 07:52 UTC, IlyaOrlov commented on Tasks/lesson_2_task_3.py
> +            self.speed = 8
Отлично! Таким образом, изменяя speed, мы количественно можем менять метод run. Вопрос для размышления: как можно реализовать качественное изменение run? Т.е. после грибов тот же персонаж при вызове метода run будет перемещаться прыжками, перелетами и т.д. Намек: self.run - просто указатель на функцию, так же как, self.speed - на значение скорости. И то, и другое можно менять.

2021-07-08 08:55 UTC, LapshinaAnnna commented
Папка создана, файлы перенесены.

Поиграли с reset hard (a.maklakov)

2021-07-08 11:09 UTC, IlyaOrlov approved these changes

2021-07-08 11:09 UTC, merged