Tokarev
IlyaOrlov/PythonCourseSTM pull request #17
Opened 2021-06-28 18:10 UTC by TokarevMI

пример игры для лекции 2 задания 3

2021-06-28 18:42 UTC, IlyaOrlov requested changes

2021-06-28 18:42 UTC, IlyaOrlov commented on Practice/Tokarev/Game_2_1.py
> +            self.speed += 1
Вопрос для размышления. Что можно сделать, что у персонажа при подборе некоторого предмета не просто скорость увеличивалась, а полностью менялась реализация метода move или run? При этом строки 102-155 меняться не должны.

2021-06-30 05:58 UTC, TokarevMI commented on Practice/Tokarev/Game_2_1.py
> +            self.speed += 1
После завершения лекции по 2-му файлу не ясно как корректно ответить на данный вопрос.
Можно добавить переменную и отслеживать ее значение в методе move по if выбирая штатный вариант работы или другой.
Думал о декараторах, но это не меняет, а дополняет работу. Прошу привести пример решения.

2021-06-30 08:22 UTC, IlyaOrlov commented on Practice/Tokarev/Game_2_1.py
> +            self.speed += 1
move - это фактически указатель на функцию. Мы можем сделать так, чтоб он указывал на какую-то другую функцию.
```python
def move(self):
    """Идти"""
    if self.speed == 0:
        print(f'Игрок {self.name} несет слишком много и не может идти')
    else:
        self.position += self.speed
        print(f'Игрок {self.name} перешёл на позицию: {self.position}')

def super_move(self):
    print('Another way to move')

self.move_action = self.move

self.move_action()  # вызов функции move

self.move_action = self.super_move

self.move_action()  # вызов функции super_move через тот же указатель
```
А если методы движения вообще вынести в отдельную иерархию классов, получится реализация паттерна стратегия: https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2021-06-30 10:24 UTC, IlyaOrlov requested changes

2021-06-30 10:24 UTC, IlyaOrlov commented on Practice/Tokarev/Game_2_1.py
> +    def move(self):
Стоит переименовать, например, в base_move (и 20-ю строку поправить соответственно), иначе мы потеряем эту исходную функцию.

2021-07-06 15:00 UTC, TokarevMI commented on Practice/Tokarev/Game_2_1.py
> +    def move(self):
так мы потеряем только для конкретного персонажа?
если да, то и не страшно, можно же будет переприсвоить обратно при поднятии другого предмета например?
self.move = self.move

2021-07-06 21:53 UTC, IlyaOrlov commented on Practice/Tokarev/Game_2_1.py
> +    def move(self):
В том-то и дело, что нельзя) self.move уже будет не self.move!

2021-07-08 11:06 UTC, IlyaOrlov requested changes

2021-07-08 11:06 UTC, IlyaOrlov commented on Practice/Tokarev/practice_3.py
> +        user_n = int(input(f"Какое число между {min_n} и {max_n} загадано?: "))
Если пользователь ввел не число, надо чтоб программа завершилась корректно, а не вылетала с исключением.

2021-07-08 11:06 UTC, IlyaOrlov commented on Practice/Tokarev/practice_3.py
> +        while text1.isdigit() is False and text1 != 'stop' and text1 != 'STOP':
Условия 9 и 11 практически одинаковые. Может все-таки можно обойтись одним циклом?

2021-07-08 21:45 UTC, IlyaOrlov requested changes

2021-07-08 21:45 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +        elif n % 3 == 0 and n % 5 != 0:
Достаточно n % 3 == 0, иначе если б n % 5 == 0, то сработало бы условие n % 15 == 0. Аналогично в строке 12.

2021-07-08 21:45 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +    return print(list(s))
s и так уже list

2021-07-13 13:04 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +            s[n - 1] = "FizzBuzz"
n-1 в качестве индекса - неуниверсальный способ, нам просто повезло, что индекс на единицу меньше элемента
Лучше для индекса вести отдельный счетчик или использовать for i, n in enumerate(s).

2021-07-16 09:23 UTC, IlyaOrlov commented on Practice/Tokarev/practice_3.py
> +        max_n = int(input(f"Введите max число которое больше или равно {min_n}: "))
Стало лучше, но:
1) вместо while user_n.isdigit() is False: лучше писать while not user_n.isdigit():
2) слишком много одинаковых циклов, имеет смысл завести отдельную функцию, отвечающую за ввод корректного числа

2021-07-16 09:25 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +    print('замена 4 пробелов:')
OK. Осталось предусмотреть вывод результата в файл.

2021-07-16 09:26 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +    to_del_s = list(reversed(to_del_s))
Он же и так list

2021-07-16 09:28 UTC, IlyaOrlov requested changes

2021-07-16 09:28 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +                i.pop(ii)
Я не против отлова исключений, но вопрос остается: они здесь случаются?

2021-07-16 12:42 UTC, TokarevMI commented on Practice/Tokarev/practice_4.py
> +                i.pop(ii)
Да, если индекс будет больше чем кол-во элементов.
На это и повесил исключение.
Что то еще надо учесть?

2021-07-16 12:46 UTC, TokarevMI commented on Practice/Tokarev/practice_4.py
> +    to_del_s = list(reversed(to_del_s))
нет.
to_del_s = reversed(to_del_s) так <class 'list_reverseiterator'>

2021-07-16 13:18 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +    to_del_s = list(reversed(to_del_s))
Точно! Спутал с методом list.reverse(), который сразу разворачивает список на месте, т.е. можно написать to_del_s.reverse() без присваиваний.

2021-07-16 13:21 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +                i.pop(ii)
Разворачивание списка как раз и позволяет предотвратить этот случай: каждый раз мы смотрим столбцы, индексы которых заведомо меньше индексов, удаленных ранее.

2021-07-16 14:23 UTC, TokarevMI commented on Practice/Tokarev/practice_4.py
> +                i.pop(ii)
я специально сделал списки разной длины
первый раз приходит индекс 3
и его нет в одном списке
так что тут будут исключения

2021-07-16 14:30 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +                i.pop(ii)
Понятно. Только тогда это уже не матрица)
Если так, то ОК: try...except нужен.

2021-07-16 14:33 UTC, TokarevMI commented on Practice/Tokarev/practice_4.py
> +                i.pop(ii)
это матрица
но с багами для Нео )

2021-07-16 14:37 UTC, IlyaOrlov commented on Practice/Tokarev/practice_4.py
> +                i.pop(ii)
ага, матрица со сбоями)

2021-07-16 15:03 UTC, IlyaOrlov approved these changes

2021-07-16 15:03 UTC, merged