Lesson 2 done.
IlyaOrlov/PythonCourseSTM pull request #20
Opened 2021-06-29 15:00 UTC by matveykortsev

2021-06-29 20:02 UTC, IlyaOrlov commented on Practice/Kortsev/game.py
> +        pass
pass здесь лишний

2021-06-29 20:07 UTC, IlyaOrlov requested changes

2021-06-29 20:07 UTC, IlyaOrlov commented on Practice/Kortsev/game.py
> +            self._move_type = self.high_move
Отлично! Будет еще круче, если типы движения вынести в отдельную иерархию классов. Согласно принципу разделения обязанностей, каждый класс должен выполнять какую-то одну обязанность. Чем меньше у класса задач, тем ниже вероятность, что его придется менять. Character будет отвечать за общее поведение персонажа, а класс Move и его дочерние классы - за типы движения (коих напрашивается немало). 
Для иллюстрации (см. пример на Python):
https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2021-07-03 09:13 UTC, IlyaOrlov commented on Practice/Kortsev/game.py
> +            self._move_type = self.high_move
Эту реализацию можно оставить, как есть. Но коммент с pass желательно поправить.

2021-07-13 12:08 UTC, matveykortsev commented on Practice/Kortsev/game.py
> +            self._move_type = self.high_move
Про Стратегию прочитал, pass убрал)

2021-07-13 12:39 UTC, IlyaOrlov approved these changes

2021-07-13 12:39 UTC, merged