Бранов - Домашняя работа № 3
IlyaOrlov/PythonCourseSTM pull request #23
Opened 2021-06-30 16:51 UTC by al-br

Домашняя работа №3

2021-06-30 21:17 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_02.py
> +    if len(word) % 2 == 1:
Универсальный вариант:
```python
word[:len(word) // 2:].lower() == word[:len(word) - len(word) // 2 - 1:-1].lower()
```

2021-06-30 21:27 UTC, IlyaOrlov requested changes

2021-06-30 21:27 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +    while True:
Слишком много while True. Можно обойтись одним циклом и несколькими доп. условиями. Если интервал не задан или число угадано - выполнять строки 12-26, иначе 28-38.
Также имеет смысл вынести код по вводу числа с проверкой и по вводу интервала в отдельные функции, чтоб меньше одинакового кода писать.
```pyhton
Если a или b не заданы:
    a, b = задать_интервал()
 # далее .. код по угадыванию числа
```

2021-07-01 11:55 UTC, al-br commented on Practice/Branov/HomeWork03/03_02.py
> +    if len(word) % 2 == 1:
спасибо, поправил

2021-07-01 11:56 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +    while True:
не знаю, насколько отдельная функция упростит, повторяющийся код не очень длинный. Циклы сократил.

2021-07-01 13:27 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +    while True:
добавил функции

2021-07-03 09:58 UTC, IlyaOrlov requested changes

2021-07-03 09:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +        c = randint(int(a), int(b))
Если get_interval будет гарантировать возврат либо None, либо целого числа, дополнительные приведения к int не нужны. То же самое для guess и d.

2021-07-03 09:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +                    a = None
a = b = c = d = None

2021-07-03 09:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +            continue
Какой смысл continue здесь и ниже? Здесь лучше написать if d и под ним весь следующий код.

2021-07-03 09:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +                print('Второе число должно быть больше первого!')
Для таких случаев лучше явно прописывать return None. Функция, конечно, и так бы вернула None в этом случае. Но прописав такой возврат явно, можно показать, что мы именно так и хотели, а не просто забыли что-то здесь вернуть. Для этой функции подойдет единый return None в 31-й строке.

2021-07-03 09:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +    if not x.isdigit():
Все-таки лучше isdecimal. Например, для "¹" isdigit вернет True, а int("¹") все равно выдаст ошибку.

2021-07-04 19:59 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +        c = randint(int(a), int(b))
поправил

2021-07-04 19:59 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +                    a = None
поправил

2021-07-04 20:00 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +            continue
да, верно. Переписал

2021-07-04 20:13 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +                print('Второе число должно быть больше первого!')
добавил, раз это красивее

2021-07-04 20:16 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +    if not x.isdigit():
спасибо, поправил. Тут я чувствую был какой-то опыт с нестандартно мыслящими пользователями? :)

2021-07-04 22:35 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +                print('Второе число должно быть больше первого!')
Я бы сказал, что так надежней. Перекрывая return'ами все выходы, мы показываем функции, что полностью ее контролируем)

2021-07-04 22:37 UTC, IlyaOrlov commented on Practice/Branov/HomeWork03/03_03.py
> +    if not x.isdigit():
Ну мало ли) Кстати, там еще один isdigit остался (строка 33).

2021-07-05 07:26 UTC, al-br commented on Practice/Branov/HomeWork03/03_03.py
> +    if not x.isdigit():
поменял

2021-07-05 09:49 UTC, IlyaOrlov approved these changes

2021-07-05 09:49 UTC, merged