Artemiev tasks
IlyaOrlov/PythonCourseSTM pull request #25
Opened 2021-07-01 17:15 UTC by ArtemijArtemev

lecture 3 's task

2021-07-03 10:16 UTC, IlyaOrlov requested changes

2021-07-03 10:16 UTC, IlyaOrlov commented on Practice/Artemiev/lecture3/task3.py
> +    low_bound = int(input())
Приглашения для ввода, типа 'enter the lower bound', лучше передавать непосредственно в input:
```python
intput('enter the lower bound')
```

2021-07-03 10:16 UTC, IlyaOrlov commented on Practice/Artemiev/lecture3/task3.py
> +            print(messages[cmp_res])
print(messages[cmp_res]) вызывается в любом случае, можно просто вынести его перед if.

2021-07-03 10:16 UTC, IlyaOrlov commented on Practice/Artemiev/lecture3/task3.py
> +while keep_play:
Непонятен смысл использования переменной в этом случае. Чтоб сделать цикл конечным, все равно не получится обойтись изменением только этой переменной.

2021-07-03 10:16 UTC, IlyaOrlov commented on Practice/Artemiev/lecture3/task3.py
> +    print('lower bound and higher bound must be integer')
В этом случае low_bound и/или higher_bound не введены, а выполнение продолжится.
Имеет смысл завести отдельную функцию, которая бы запрашивала у пользователя в цикле целое число, и применить эту функцию во всех трех случаях ввода числа (low_bound, higher_bound, user_input).

2021-07-09 20:29 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture3/task3.py
> +    print('lower bound and higher bound must be integer')
поправил

2021-07-10 08:35 UTC, IlyaOrlov approved these changes

2021-07-10 08:35 UTC, merged