Бранов - Домашняя работа № 4
IlyaOrlov/PythonCourseSTM pull request #26
Opened 2021-07-07 10:32 UTC by al-br

Бранов - Домашняя работа № 4

2021-07-08 10:58 UTC, IlyaOrlov requested changes

2021-07-08 10:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork04/04_03.py
> +temp = arr.copy()
Можно реализовать и без вспомогательного массива. В list.index(x[, start[, end]]) можно указать, с какого элемента начинать поиск.

2021-07-08 10:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork04/04_03.py
> +    arr.reverse()
Что делается в строках 19-21?

2021-07-08 10:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork04/04_04.py
> +    if isinstance(path, IOBase):
Если path - путь к файлу, это тоже тип str.

2021-07-08 10:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork04/04_04.py
> +            for line in file:
Писать в тот же файл, из которого читаешь - неблагодарное дело)

2021-07-08 10:58 UTC, IlyaOrlov commented on Practice/Branov/HomeWork04/04_06.py
> +        idx_to_kill = set(idx_to_kill)
Можно сразу сделать idx_to_kill множеством.

2021-07-08 11:36 UTC, al-br commented on Practice/Branov/HomeWork04/04_03.py
> +    arr.reverse()
метод remove удаляет первый элемент, совпавший с указанным. Пробегать массив он начинает с начала.  Поэтому, в случае. если в массиве будут одинаковые элементы, как в нашем случае, он найдет первый, поставит его на нужное место, потом найдет второй, но удалит вместо него первый, а второй останется на старом месте. А при развороте массива, сколько бы повторяющихся элементов в нем не было, он будет убирать их с конца и расставлять на нужные места.
Поэтому 19 строка разворачивает массив к лесу передом, 20 удаляет текущий элемент, 21 разворачивает массив обратно.

2021-07-08 11:41 UTC, al-br commented on Practice/Branov/HomeWork04/04_03.py
> +temp = arr.copy()
я думал, это часть условия :) тогда прошу уточнить ТЗ. Нужны официальные правки заказчика :)

2021-07-08 11:45 UTC, al-br commented on Practice/Branov/HomeWork04/04_06.py
> +        idx_to_kill = set(idx_to_kill)
да, точно. Поправил

2021-07-08 11:46 UTC, al-br commented on Practice/Branov/HomeWork04/04_04.py
> +            for line in file:
не любишь шампанское?)
Переделаю

2021-07-08 21:49 UTC, IlyaOrlov commented on Practice/Branov/HomeWork04/04_03.py
> +temp = arr.copy()
Это не условие) Это вопрос эффективности алгоритма. Дополнительный список - это расход памяти и времени.

2021-07-08 21:50 UTC, IlyaOrlov commented on Practice/Branov/HomeWork04/04_04.py
> +            for line in file:
Да, стоит переделать)

2021-07-12 15:46 UTC, al-br commented on Practice/Branov/HomeWork04/04_03.py
> +temp = arr.copy()
переписал

2021-07-12 15:47 UTC, al-br commented on Practice/Branov/HomeWork04/04_03.py
> +    arr.reverse()
логика изменена

2021-07-12 16:38 UTC, al-br commented on Practice/Branov/HomeWork04/04_04.py
> +    if isinstance(path, IOBase):
исправлено

2021-07-12 16:38 UTC, al-br commented on Practice/Branov/HomeWork04/04_04.py
> +            for line in file:
исправлено

2021-07-13 08:33 UTC, IlyaOrlov approved these changes

2021-07-13 08:33 UTC, merged