lesson2_task_1_2
IlyaOrlov/PythonCourseSTM pull request #27
Opened 2021-07-09 15:06 UTC by Sapeg12

2021-07-10 08:31 UTC, IlyaOrlov requested changes

2021-07-10 08:31 UTC, IlyaOrlov commented on Practice/isapegov/lesson_2/lesson2_tast_1_task_2.py
> +(test(a, b))
Зачем test брать в скобки?

2021-07-10 08:31 UTC, IlyaOrlov commented on Practice/isapegov/lesson_2/lesson2_tast_1_task_2.py
> +    print(f'Максимальное число: {c}')
Здесь и в 21-й строке выражение можно прямо на место переменной **с** подставить.

2021-07-10 08:46 UTC, Sapeg12 reviewed
Поправил.

2021-07-10 08:46 UTC, Sapeg12 commented on Practice/isapegov/lesson_2/lesson2_tast_1_task_2.py
> +(test(a, b))
Упс, это опечатка...
Изначально я написал print(test(a, b)), выводилось помимо максимального числа  значение "none", убрал print, а вот скобки оставил.

2021-07-11 17:33 UTC, Sapeg12 commented on Practice/isapegov/lesson_2/lesson2_tast_1_task_2.py
> +    print(f'Максимальное число: {c}')
Да, можно сделать так.
a = (a > b) if (a > b) else b
    print(f'Максимальное число: {a}')

2021-07-11 21:27 UTC, IlyaOrlov commented on Practice/isapegov/lesson_2/lesson2_tast_1_task_2.py
> +    print(f'Максимальное число: {c}')
Не, (a > b) это True. Т.е. если a больше b, то a станет равно True.
Лучше так print(f'Максимальное число: {a if (a > b) else b}')

2021-07-11 21:29 UTC, Sapeg12 commented on Practice/isapegov/lesson_2/lesson2_tast_1_task_2.py
> +    print(f'Максимальное число: {c}')
Понял, я пробовал тоже самое, только без {}, видимо данных скобок и не хватало.

2021-07-12 07:52 UTC, Sapeg12 commented on Practice/isapegov/lesson_2/lesson2_tast_1_task_2.py
> +    print(f'Максимальное число: {c}')
#1
a = int(input('Число a: '))
b = int(input('Число b: '))


def test(a, b):

    print(f'Максимальное число: {a if (a > b) else b}')

test(a, b)

#2
a = int(input('Число a: '))
b = int(input('Число b: '))


def test(a, b):
    return a if (a > b) else b

print(test(a, b))

2021-07-13 12:45 UTC, IlyaOrlov requested changes

2021-07-13 12:45 UTC, IlyaOrlov commented on Practice/isapegov/lesson_3/lesson_3_task_2.py
> +def Palindrome(a):
Название функции в нижнем регистре (PEP8)

2021-07-13 12:45 UTC, IlyaOrlov commented on Practice/isapegov/lesson_2/lesson2_task_3.py
> +        if r == 1:
r не может одновременно быть 1, 2 и 3, поэтому в 26-й и 29-й строках стоит использовать elif и else.

2021-07-13 12:45 UTC, IlyaOrlov commented on Practice/isapegov/lesson_2/lesson2_task_3.py
> +            self.x += self.run
ОК. Вопрос для размышления. Если при каком-то условии анимация move должна меняться кардинально, как можно осуществить подмену метода move (чтоб название было тоже, а тело - другое)?

2021-07-13 13:37 UTC, IlyaOrlov commented on Practice/isapegov/lesson_2/lesson2_task_3.py
> +            self.x += self.run
https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2021-07-15 10:49 UTC, Sapeg12 commented on Practice/isapegov/lesson_2/lesson2_task_3.py
> +            self.x += self.run
Тут не получилось, но я обязательно вернусь к этому позже.

2021-07-15 12:52 UTC, IlyaOrlov approved these changes

2021-07-15 12:52 UTC, merged