Lesson_2_task_1-3
IlyaOrlov/PythonCourseSTM pull request #28
Opened 2021-07-11 07:53 UTC by LapshinaAnnna

2021-07-11 12:31 UTC, IlyaOrlov requested changes

2021-07-11 12:31 UTC, IlyaOrlov commented on Practice/Lapshina/lesson_3_task_1.py
> +    if input_value == 'stop':
По заданию слово должно быть регистронезависимым (т.е. допускаются варианты "Stop", "STOP" и т.д.)

2021-07-11 12:31 UTC, IlyaOrlov commented on Practice/Lapshina/lesson_3_task_3.py
> +    if a < b:
Сейчас во всех случаях проверяются делаются все три проверки (>, <, ==). Но если хотя бы одна из проверок вернула True, остальные выполнять уже бессмысленно. Поэтому альтернативы лучше писать через elif и else.

2021-07-11 12:31 UTC, IlyaOrlov commented on Practice/Lapshina/lesson_3_task_3.py
> +        return True
Если числа совпали, функция возвращает True. Иначе - ничего (фактически неявно возвращается None). Хотя None и преобразуется в False, лучше явно вернуть False, когда числа не совпали. Во-первых, с функцией проще работать, когда она в любом случае возвращает значения одного типа. Во-вторых, явный return показывает, что так и задумывалось, а не просто забыли такой исход.

2021-07-12 12:14 UTC, LapshinaAnnna commented
исправлено

2021-07-16 12:11 UTC, IlyaOrlov approved these changes

2021-07-16 12:11 UTC, merged