Бранов - Домашняя работа № 5.
IlyaOrlov/PythonCourseSTM pull request #31
Opened 2021-07-14 13:01 UTC by al-br

Бранов - Домашняя работа № 5.

2021-07-14 21:30 UTC, IlyaOrlov commented on Practice/Branov/HomeWork05/05_03.py
> +    def __init__(self, input_file, output_file):
OK, можно и без mktemp, но нужен один файл и для чтения, и для записи, т.к. он по сути должен выполнять роль хранилища для значения переменной.

2021-07-14 21:32 UTC, IlyaOrlov requested changes

2021-07-14 21:32 UTC, IlyaOrlov commented on Practice/Branov/HomeWork05/05_03.py
> +                return file
Здесь должно возвращаться содержимое файла.

2021-07-14 21:32 UTC, IlyaOrlov commented on Practice/Branov/HomeWork05/05_03.py
> +        with open(self.output_file, 'a') as file:
Файл хранит конкретное значение переменной, поэтому его стоит открывать на запись, а не на дозапись.

2021-07-15 13:30 UTC, al-br commented on Practice/Branov/HomeWork05/05_03.py
> +    def __init__(self, input_file, output_file):
исправил

2021-07-15 13:32 UTC, al-br commented on Practice/Branov/HomeWork05/05_03.py
> +                return file
исправлено

2021-07-15 13:32 UTC, al-br commented on Practice/Branov/HomeWork05/05_03.py
> +        with open(self.output_file, 'a') as file:
исправлено

2021-07-16 09:31 UTC, IlyaOrlov requested changes

2021-07-16 09:31 UTC, IlyaOrlov commented on Practice/Branov/HomeWork05/05_03.py
> +                    return line
Если значение, которое мы записали в файл? включает перенос строки, мы сможем вытащить только часть до символа переноса (первую line). Лучше использовать file.read()

2021-07-16 10:19 UTC, al-br commented on Practice/Branov/HomeWork05/05_03.py
> +                    return line
резонно. применил file.read()

2021-07-16 10:27 UTC, IlyaOrlov approved these changes

2021-07-16 10:27 UTC, merged