Lesson 3 homework done
IlyaOrlov/PythonCourseSTM pull request #32
Opened 2021-07-15 14:22 UTC by matveykortsev

2021-07-16 09:51 UTC, IlyaOrlov requested changes

2021-07-16 09:51 UTC, IlyaOrlov commented on Practice/Kortsev/lesson3.py
> +            print(f'Your digit is {int(number)}')
Не совсем то, что требовалось. Мы должны накапливать вводимые пользователем цифры в одну строку и по слову stop выводить получившееся в итоге число.

2021-07-16 09:51 UTC, IlyaOrlov commented on Practice/Kortsev/lesson3.py
> +    word = input('Type word to check for palindrome: ').lower()
Если передавать слово для проверки в качестве аргумента функции, а не задавать его внутри функции, то функция будет более универсальной.

2021-07-16 09:51 UTC, IlyaOrlov commented on Practice/Kortsev/lesson3.py
> +        elif int(guess_number) == number:
guess_number = int(guess_number) можно сделать один раз перед 36-й строкой, а 36-ю строку начать с if.

2021-07-16 09:51 UTC, IlyaOrlov commented on Practice/Kortsev/lesson3.py
> +        if int(guess_number) < number:
Если убрать continue и вместо if int(guess_number) < number написать просто else (т.к. если число не равно и не больше другого, то оно 100% меньше), получится более очевидный код.

2021-07-16 19:27 UTC, matveykortsev commented on Practice/Kortsev/lesson3.py
> +            print(f'Your digit is {int(number)}')
Ага, вот не до конца понял условие, без проблем, поправил

2021-07-17 00:58 UTC, IlyaOrlov commented on Practice/Kortsev/lesson3.py
> +            print(f'Your digit is {int(number)}')
Нет. Вот как раз вывод print(f'Your digit is {int(line)}') должен быть в строке 12 и после него сразу brake. Т.е. копим, копим цифры... потом - stop: выводим, что получилось, и выходим.

2021-07-17 13:12 UTC, IlyaOrlov approved these changes

2021-07-17 13:12 UTC, merged