task: pep8task
IlyaOrlov/PythonCourseSTM pull request #4
Opened 2021-06-24 19:33 UTC by ArtemijArtemev

2021-06-24 20:04 UTC, IlyaOrlov requested changes

2021-06-24 20:04 UTC, IlyaOrlov commented on Practice/Artemiev/pep8task.py
> +import sys
Нужны комментарии: что и почему исправлено.

2021-06-25 16:09 UTC, ArtemijArtemev commented on Practice/Artemiev/pep8task.py
> +import sys
комментарии добавлены

2021-06-25 16:19 UTC, IlyaOrlov approved these changes

2021-06-25 16:19 UTC, merged