Artemiev tasks 6
IlyaOrlov/PythonCourseSTM pull request #43
Opened 2021-08-23 12:38 UTC by ArtemijArtemev

2021-08-23 20:14 UTC, IlyaOrlov requested changes

2021-08-23 20:14 UTC, IlyaOrlov commented on Practice/Artemiev/lecture6/task1.py
> +        self.par_list, self.pos = text.split(split_c), -1
Теряется смысл итератора. Так мы сразу весь результат получаем и только возвращаем его порционно. Если у нас text большой, мы вместо того, чтоб его читать по кусочкам, экономя память, сделаем еще и список  такой же большой.

2021-08-23 20:14 UTC, IlyaOrlov commented on Practice/Artemiev/lecture6/task1.py
> +while p_item:
А что не через for?

2021-08-23 20:14 UTC, IlyaOrlov commented on Practice/Artemiev/lecture6/task2.py
> +    f = open(path, 'r')
Лучше через менеджер контекста with.

2021-08-23 20:14 UTC, IlyaOrlov commented on Practice/Artemiev/lecture6/task2.py
> +    while line:
Поскольку файловый объект в Питоне сам является итератором здесь его можно просто обходить через for line in f.

2021-08-23 20:14 UTC, IlyaOrlov commented on Practice/Artemiev/lecture7/task1.py
> +        if cur_day.weekday() not in [5, 6]:
Сюда больше просится {5, 6} или даже frozenset. И in должен быстрее сработать, и смысл больше подходит.

2021-09-07 18:27 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture6/task1.py
> +        self.par_list, self.pos = text.split(split_c), -1
поправил

2021-09-07 18:28 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture6/task1.py
> +while p_item:
да так удобней

2021-09-07 18:28 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture6/task2.py
> +    f = open(path, 'r')
ага. сделал

2021-09-07 18:28 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture6/task2.py
> +    while line:
да так лучше

2021-09-07 18:29 UTC, ArtemijArtemev commented on Practice/Artemiev/lecture7/task1.py
> +        if cur_day.weekday() not in [5, 6]:
да данные изменяются

2021-09-07 19:48 UTC, IlyaOrlov approved these changes

2021-09-07 19:48 UTC, merged