Задания 9
IlyaOrlov/PythonCourseSTM pull request #44
Opened 2021-08-30 12:30 UTC by TokarevMI

2021-08-31 09:29 UTC, IlyaOrlov requested changes

2021-08-31 09:29 UTC, IlyaOrlov commented on Practice/Tokarev/practice_9.py
> +    for arg in args:
Не упростит ли код объединение этого цикла с циклом в строке 35?

2021-08-31 09:29 UTC, IlyaOrlov commented on Practice/Tokarev/practice_9.py
> +    if __name__ == '__main__':
Лишняя строка.

2021-08-31 14:00 UTC, TokarevMI commented on Practice/Tokarev/practice_9.py
> +    for arg in args:
Тогда если в начале будут числа, например 4 и 5, а после строка "Слово"
не выйдет собрать в "45Слово"
получится "9Слово", поскольку в начале мы не знаем что есть строка и работаем как с числом.

2021-08-31 18:58 UTC, IlyaOrlov commented on Practice/Tokarev/practice_9.py
> +    for arg in args:
ОК. Тогда оставим так.

2021-09-01 22:24 UTC, IlyaOrlov requested changes

2021-09-01 22:24 UTC, IlyaOrlov commented on Practice/Tokarev/practice_10.py
> +        while self.flag1:
flag1 используется только внутри run. Имеет смысл сделать его локальной переменной, а не атрибутом экземпляра.
Аналогично с listall.

2021-09-01 22:24 UTC, IlyaOrlov commented on Practice/Tokarev/server.py
> +                self._connection.send(bytes(self.dict_cod.get(data.decode()), 'utf-8'))
Нехорошо, что data.decode() и dict_cod.get() вызываются несколько раз с одними и теми же параметрами. Стоит улучшить re-use кода.

2021-09-01 22:24 UTC, IlyaOrlov commented on Practice/Tokarev/server.py
> +        print('Connection from address {}'.format(self._address))
Стоит придерживаться одного стиля: либо форматная строка, либо метод format().

2021-09-01 22:24 UTC, IlyaOrlov commented on Practice/Tokarev/server.py
> +        self._connection.send(bytes(str(self.dict_cod.keys()), 'utf-8'))
Здесь и ниже: bytes(строка, 'utf-8') можно заменить на строка.encode(), где utf-8 - по умолчанию.

2021-09-01 22:24 UTC, IlyaOrlov commented on Practice/Tokarev/practice_10_2.py
> +        temp = {'name': self.uname, 'age': self.uage}
Почему бы не хранить в TcpClient2 экземпляр класса User и передавать его на сервер при помощи pickle? Иначе нарушается принцип инкапсуляции.

2021-09-01 22:24 UTC, IlyaOrlov commented on Practice/Tokarev/practice_10_3.py
> +            # Раскоментить стоку ниже и вставить в if чтобы отсечь мусор
А если поэкспериментировать с регулярными выражениями, чтоб исключить мусор?

2021-09-01 22:24 UTC, IlyaOrlov commented on Practice/Tokarev/practice_10_3.py
> +    while poz < len(web_page):
Стоит разнести по разным функциям код поиска ссылок и код проверки этих ссылок.

2021-09-07 19:38 UTC, IlyaOrlov approved these changes

2021-09-07 19:38 UTC, merged