Branov
IlyaOrlov/PythonCourseSTM pull request #7
Opened 2021-06-25 09:27 UTC by al-br

ДЗ 1 и 2

2021-06-25 09:42 UTC, al-br commented
Исправлено ДЗ 2

2021-06-25 10:33 UTC, IlyaOrlov commented on Practice/Branov/HomeWork_02.py
> +    print(f'Самое большое число из {args}: ', max(args))
Лучше так: f'Самое большое число из {args}: {max(args)}'.

2021-06-25 10:41 UTC, IlyaOrlov requested changes

2021-06-25 10:41 UTC, IlyaOrlov commented on Practice/Branov/HomeWork_02.py
> +    nick.move()
Отлично! Такая вопрос для размышления. Что если при подборе некоторых артефактов тот же метод move должен меняться кардинально (например, персонаж начинает двигаться прыжками, или летать)? Т.е. персонаж тот же, имя метода для движения move - то же, но реализация его после подбора артефакта становится совсем другой.

2021-06-25 10:41 UTC, IlyaOrlov commented on Practice/Branov/pep8task.py
> +            f = open(output, 'r')
А нужно ли строки 24-25 вносить в цикл? Может, лучше наоборот сдвинуть их влево?

2021-06-27 06:19 UTC, al-br commented on Practice/Branov/HomeWork_02.py
> +    print(f'Самое большое число из {args}: ', max(args))
исправил

2021-06-27 06:39 UTC, al-br commented on Practice/Branov/HomeWork_02.py
> +    nick.move()
1. Сделать отдельные методы на каждый вариант движения
2. Переработать структуру предмета. Например:
    {'booze': {'statst':{'agility': -2, 'intelligence': -4},'actions':['stagger']}}
3. Переработать все методы взаимодействия с предметами, с учетом новой структуры. Action будет записываться в новую переменную в __init__ - self.action
4. Метод move превратится в переключатель. который в зависимости от значения в переменной self.action будет дергать соответствующий метод движения

2021-06-27 06:49 UTC, al-br commented on Practice/Branov/pep8task.py
> +            f = open(output, 'r')
исправил

2021-06-27 09:01 UTC, IlyaOrlov commented on Practice/Branov/HomeWork_02.py
> +    nick.move()
Супер. Меня, в первую очередь, интересовал вариант 4.

2021-06-27 09:03 UTC, IlyaOrlov requested changes

2021-06-27 09:03 UTC, IlyaOrlov commented on Practice/Branov/pep8task.py
> +import sys
Не хватает ещё комментов, где, что и почему исправлено.

2021-06-27 11:11 UTC, al-br commented on Practice/Branov/pep8task.py
> +import sys
добавил комментарии

2021-06-27 11:12 UTC, al-br commented on Practice/Branov/HomeWork_02.py
> +    nick.move()
Доработал.

2021-06-27 17:02 UTC, IlyaOrlov commented on Practice/Branov/HomeWork_02.py
> +    nick.move()
Здорово! Получилась реализация паттерна Стратегия) https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2021-06-27 17:05 UTC, IlyaOrlov commented on Practice/Branov/pep8task.py
> +if __name__ == '__main__':  # чтобы не дублировать данный вызов при импорте кода в другой файл
Отличное предложение! Мы еще отдельно разберем эту конструкцию if __name__ == '__main__'

2021-06-27 17:05 UTC, IlyaOrlov approved these changes

2021-06-27 17:05 UTC, merged